res_group: sso
res_group_location: "canadacentral"
storage_class: Standard_LRS
virtual_network_cidr: 192.168.33.0/24
username: "ansible"
password: "Password1!"
  
centos_vm_size: Standard_D2_v3
#windows_vm_size: Standard_D4s_v3
windows_vm_size: Standard_D2_v3

ip_addresses:
  ad: "192.168.33.10"
  adfs: "192.168.33.11"
  winapp: "192.168.33.12"
  jbossapp: "192.168.33.13"

sso_dns_domain: "sso.doogie.ca"

windows_groups:
  - name: Finance 
  - name: Sales

windows_users:
  - name: "RobertH"
    firstname: "Robert"
    lastname: "Hatley"
    password: "{{ password }}"
    groups:
      - Finance
  - name: "DonaldD"
    firstname: "Donald"
    lastname: "Duck"
    password: "{{ password }}"
    groups:
      - Sales
  - name: "demoadmin"
    firstname: "Demo"
    lastname: "Admin"
    password: "{{ password }}"
    groups:
      - "Domain Admins"

letsencrypt_acme_directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
#letsencrypt_acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
letsencrypt_account_key_src: "files/letsencrypt/account.key"
letsencrypt_dh_params_src: "files/letsencrypt/dhparams.out"
letsencrypt_adfs_key_src: "files/letsencrypt/adfs.key"
letsencrypt_adfs_csr_src: "files/letsencrypt/adfs.csr"
letsencrypt_adfs_crt_src: "files/letsencrypt/adfs.crt"
letsencrypt_adfs_pfx_src: "files/letsencrypt/adfs.pfx"
letsencrypt_adfs_pfx_dest: "c:\\adfs.pfx"
letsencrypt_adfs_fullchain_src: "files/letsencrypt/adfs_fullchain.crt"
letsencrypt_adfs_chain_src: "files/letsencrypt/adfs_intermediate.crt"
