res_group: sso
res_group_location: "canadacentral"
storage_class: Standard_LRS
virtual_network_cidr: 192.168.33.0/24
username: "ansible"
password: "Password1!"
  
default_rhel_vm_size: Standard_D2_v3
#windows_vm_size: Standard_D4s_v3
default_windows_vm_size: Standard_D2_v3

demo_jboss_sso_adfs_environment:
  - name: ad
    machinename: "advm"
    internal_ip_address: "192.168.33.10"
    public_ip: true
    vm_size: "{{ default_windows_vm_size }}"
  # - name: adfs
  #   machinename: "adfsvm"
  #   internal_ip_address: "192.168.33.11"
  #   public_ip: true
  #   vm_size: "{{ default_windows_vm_size }}"
  # - name: winapp
  #   machinename: "winappvm"
  #   internal_ip_address: "192.168.33.12"
  #   public_ip: true
  #   vm_size: "{{ default_windows_vm_size }}"
  - name: rhsso
    machinename: "rhssovm"
    public_ip: true
    internal_ip_address: "192.168.33.13"
    vm_size: "{{ default_rhel_vm_size }}"

ip_addresses:
  ad: "192.168.33.10"
  # adfs: "192.168.33.11"
  # winapp: "192.168.33.12"
  rhsso: "192.168.33.13"
  

sso_dns_domain: "sso.doogie.ca"

windows_groups:
  - name: Finance 
  - name: Sales

windows_users:
  - name: "RobertH"
    firstname: "Robert"
    lastname: "Hatley"
    password: "{{ password }}"
    groups:
      - Finance
  - name: "DonaldD"
    firstname: "Donald"
    lastname: "Duck"
    password: "{{ password }}"
    groups:
      - Sales
  - name: "demoadmin"
    firstname: "Demo"
    lastname: "Admin"
    password: "{{ password }}"
    groups:
      - "Domain Admins"

# adfs_base_directory: "c:\\adfs"
# adfs_setup_powershell_src: "templates/adfs/setup_adfs.ps1.j2"
# adfs_setup_powershell_dest: "{{ adfs_base_directory }}\\setup_adfs.ps1"
# adfs_federation_display_name: "Doogie SSO"
# adfs_service_account_name: "FsGmsa"

#letsencrypt_acme_directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
letsencrypt_acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
letsencrypt_account_key_src: "files/letsencrypt/account.key"
letsencrypt_dh_params_src: "files/letsencrypt/dhparams.out"

# letsencrypt_adfs_key_src: "files/letsencrypt/adfs.key"
# letsencrypt_adfs_csr_src: "files/letsencrypt/adfs.csr"
# letsencrypt_adfs_crt_src: "files/letsencrypt/adfs.crt"
# letsencrypt_adfs_pfx_src: "files/letsencrypt/adfs.pfx"
# letsencrypt_adfs_pfx_dest: "{{ adfs_base_directory }}\\adfs.pfx"
# letsencrypt_adfs_fullchain_src: "files/letsencrypt/adfs_fullchain.crt"
# letsencrypt_adfs_chain_src: "files/letsencrypt/adfs_intermediate.crt"

letsencrypt_rhsso_key_src: "files/letsencrypt/rhsso.{{ sso_dns_domain }}.key"
letsencrypt_rhsso_key_dest: "/etc/pki/tls/private/rhsso.{{ sso_dns_domain }}.key"
letsencrypt_rhsso_csr_src: "files/letsencrypt/rhsso.{{ sso_dns_domain }}.csr"
letsencrypt_rhsso_crt_src: "files/letsencrypt/rhsso.{{ sso_dns_domain }}.crt"
letsencrypt_rhsso_crt_dest: "/etc/pki/tls/certs/rhsso.{{ sso_dns_domain }}.crt"
letsencrypt_rhsso_fullchain_src: "files/letsencrypt/rhsso.{{ sso_dns_domain }}_fullchain.crt"
letsencrypt_rhsso_fullchain_dest: "/etc/pki/tls/certs/rhsso.{{ sso_dns_domain }}_fullchain.crt"
letsencrypt_rhsso_chain_src: "files/letsencrypt/rhsso.{{ sso_dns_domain }}_intermediate.crt"
letsencrypt_rhsso_chain_dest: "/etc/pki/tls/certs/rhsso.{{ sso_dns_domain }}_intermediate.crt"


# winapp_site_directory: "c:\\sites"
# winapp_app_pool: winapp
# winapp_site_name: winapp
# winapp_site_hostname: winapp.sso.doogie.ca
# winapp_dest: "{{ winapp_site_directory }}\\winapp"